sonar.projectKey=yassemine-al_projet-genie-logiciel-groupe4
sonar.organization=yassemine-al


sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes


sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=src/main/java/addressBook/GuiMain.java, src/main/java/addressBook/Main.java